name = "testing"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = []
features = ["maps", ]
min_version = "0.20.7"

[author]
  name = "Nate Nichols"
  homepage = "http://nqthqn.com"